// SAMPLE DATA – synthetic, not real. Generated by tests/support/make-sample-dataset.js (STO-003).
window.CFE_PUBLISHED_MANIFEST = {
  "schema": "cfe.manifest",
  "schema_version": 1,
  "publication_id": "sample-2026-10-05",
  "published_utc": "2026-10-05T09:00:00Z",
  "publisher": "Sample data generator",
  "app_version": "sample-generator 1",
  "dataset_schema_version": 1,
  "data_as_of": "2025-12-19",
  "payload_sha256": "5e65154ab7e070072f0e65284d92d2bd94ca826a7ba8c7ee299aee8a28cd6355",
  "sources": [
    {
      "file_id": "7d9ec8aa3e66",
      "name": "legacy-config-basic.json",
      "size": 153200,
      "last_modified": null,
      "sha256": "7d9ec8aa3e66bb8f6df0962e50fcdf4315a36afd7866c135e1e397bdeca95026",
      "imported_utc": "2026-10-05T09:00:00Z",
      "source_system": "Synthetic test fixture (TST-002)",
      "parser": "json",
      "parser_version": "1",
      "mapping_profile": "legacy-config",
      "sheet": null,
      "header_row": null,
      "rows_read": 245,
      "rows_used": 245,
      "as_of": null
    }
  ],
  "counts": {
    "references": 2,
    "po": 4,
    "resource_rules": 14,
    "people": 11,
    "actual_rows_in": 200,
    "actual_aggregates": 16,
    "invoices": 10,
    "expenses": 9,
    "fx_rates": 5,
    "ot_rules": 3,
    "calendars": 8
  },
  "validation": {
    "errors": 0,
    "warnings": []
  },
  "minimisation": {
    "policy": "Synthetic sample: fictitious names and amounts; actuals published as monthly aggregates (ADR-016)",
    "person_names": "included"
  },
  "deployment": {
    "display_name": "Finance Engine (sample)",
    "reporting_currency": "GBP"
  },
  "publications": [
    {
      "publication_id": "sample-2026-10-05",
      "published_utc": "2026-10-05T09:00:00Z",
      "publisher": "Sample data generator",
      "action": "publish",
      "counts": {
        "references": 2,
        "po": 4,
        "resource_rules": 14,
        "people": 11,
        "actual_rows_in": 200,
        "actual_aggregates": 16,
        "invoices": 10,
        "expenses": 9,
        "fx_rates": 5,
        "ot_rules": 3,
        "calendars": 8
      }
    }
  ],
  "sample": true
};
